services:
  # frontend:
  
  backend-database:
    build: ./backend/database/
    container_name: IDEAFINDER_DB
    networks:
      - ideafinder
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
  
  backend-finder-tool:
    build: ./backend/finder_tool/
    container_name: IDEAFINDER_TOOL
    depends_on:
      - backend-database
    networks:
      - ideafinder
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=backend-database
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  # backend-api:
  #   build: ./backend/api/
  #   container_name: IDEAFINDER_API
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - ideafinder
  #   restart: unless-stopped
  

networks:
  ideafinder:

volumes:
  postgres_data:

