import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/home/header";
import Footer from "./components/home/footer";
import { Rochester } from 'next/font/google';
import SessionProvider from "./components/SessionProvider"

const sansation = Rochester({
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>)
{
  return (
    <html lang="en" className="overscroll-y-contain">
      <body>
        <SessionProvider>
          <Header/>
          {children}
          <Footer/>
        </SessionProvider>
      </body>
    </html>
  );
}
