export default function PrivacyPolicy() {
  
  // FIXME: update for prod
  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <div className="rounded-xl p-8 shadow-lg">
        <h1 className="text-3xl font-bold mb-8 text-white">Privacy Policy</h1>
        <h2 className="text-2xl font-semibold mb-6 text-white">1. Privacy at a Glance</h2>
        <h3 className="text-xl font-semibold mb-4 text-white">General Information</h3>
        <p className="text-gray-300 mb-6 leading-relaxed">The following notes provide a simple overview of what happens to your personal data when you visit this website. Personal data are all data with which you can be personally identified. For detailed information on data protection, please refer to our full Privacy Policy below.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Data Collection on This Website</h3>
        <h4 className="text-lg font-medium mb-3 text-white">Who is responsible for data collection on this website?</h4>
        <p className="text-gray-300 mb-6 leading-relaxed">Data processing on this website is carried out by the website operator. You can find their contact details in the section "Notice on the Data Controller" of this Privacy Policy.</p>
        <h4 className="text-lg font-medium mb-3 text-white">How do we collect your data?</h4>
        <p className="text-gray-300 mb-4 leading-relaxed">Your data are collected in part because you provide them to us. This may include data that you enter into a contact form, for example.</p>
        <p className="text-gray-300 mb-6 leading-relaxed">Other data are collected automatically or after your consent when you visit the website by our IT systems. These are primarily technical data (e.g., web browser, operating system, or time of page access). This data collection occurs automatically as soon as you enter this website.</p>
        <h4 className="text-lg font-medium mb-3 text-white">What do we use your data for?</h4>
        <p className="text-gray-300 mb-6 leading-relaxed">Part of the data is collected to ensure the website is provided error-free. Other data may be used to analyze your user behavior. If contracts are concluded or initiated via the website, the data transmitted will also be processed for contract offers, orders, or other service requests.</p>
        <h4 className="text-lg font-medium mb-3 text-white">What rights do you have regarding your data?</h4>
        <p className="text-gray-300 mb-4 leading-relaxed">You have the right at any time to receive free information about the origin, recipients, and purpose of your stored personal data. You also have the right to request correction or deletion of this data. If you have given consent to data processing, you may revoke this consent at any time for the future. You also have the right under certain circumstances to request the restriction of the processing of your personal data. Furthermore, you have the right to lodge a complaint with the competent supervisory authority.</p>
        <p className="text-gray-300 mb-6 leading-relaxed">For this purpose as well as for further questions on the subject of data protection, you can contact us at any time.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Analysis Tools and Third-Party Tools</h3>
        <p className="text-gray-300 mb-4 leading-relaxed">When you visit this website, your surfing behavior may be statistically evaluated. This is done primarily with so-called analysis programs.</p>
        <p className="text-gray-300 mb-8 leading-relaxed">Detailed information on these analysis programs can be found in the following Privacy Policy.</p>
        <h2 className="text-2xl font-semibold mb-6 text-white">2. Hosting</h2>
        <p className="text-gray-300 mb-6 leading-relaxed">We host the content of our website with the following provider:</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Hetzner</h3>
        <p className="text-gray-300 mb-4 leading-relaxed">Provider is Hetzner Online GmbH, Industriestr. 25, 91710 Gunzenhausen (hereinafter "Hetzner").</p>
        <p className="text-gray-300 mb-4 leading-relaxed">Details can be found in Hetzner's Privacy Policy: <a href="https://www.hetzner.com/de/legal/privacy-policy/" target="_blank" rel="noopener noreferrer" className="text-[#7A1CAC] hover:text-[#AD49E1] transition-colors duration-200 underline">https://www.hetzner.com/de/legal/privacy-policy/</a>.</p>
        <p className="text-gray-300 mb-6 leading-relaxed">The use of Hetzner is based on Art. 6 (1) lit. f GDPR. We have a legitimate interest in a reliable presentation of our website. If the relevant consent has been obtained, processing is carried out exclusively on the basis of Art. 6 (1) lit. a GDPR and § 25 (1) TDDDG, insofar as the consent includes the storage of cookies or access to information on the user's device (e.g., device fingerprinting) within the meaning of the TDDDG. Consent may be revoked at any time.</p>
        <h4 className="text-lg font-medium mb-3 text-white">Order Processing</h4>
        <p className="text-gray-300 mb-8 leading-relaxed">We have concluded a contract on order processing (AVV) for the use of the above-mentioned service. This is a contract required under data protection law that ensures the processor only processes our website visitors' personal data on our instructions and in compliance with the GDPR.</p>
        <h2 className="text-2xl font-semibold mb-6 text-white">3. General Notes and Mandatory Information</h2>
        <h3 className="text-xl font-semibold mb-4 text-white">Data Protection</h3>
        <p className="text-gray-300 mb-4 leading-relaxed">The operators of these pages take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with statutory data protection regulations and this Privacy Policy.</p>
        <p className="text-gray-300 mb-4 leading-relaxed">When you use this website, various personal data are collected. Personal data are data with which you can be personally identified. This Privacy Policy explains which data we collect and what we use it for. It also explains how and for what purpose this happens.</p>
        <p className="text-gray-300 mb-6 leading-relaxed">Please note that data transmission over the Internet (e.g., when communicating by e-mail) may have security gaps. Complete protection of data against access by third parties is not possible.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Notice on the Data Controller</h3>
        <p className="text-gray-300 mb-4 leading-relaxed">The data controller for processing on this website is:</p>
        <p className="text-gray-300 mb-4 leading-relaxed">Example Company<br />
        Musterweg 10<br />
        90210 Musterstadt</p>
        <p className="text-gray-300 mb-4 leading-relaxed">Phone: +49 (0) 123 44 55 66<br />
        E-mail: info@beispielfirma.de</p>
        <p className="text-gray-300 mb-6 leading-relaxed">The data controller is the natural or legal person who alone or jointly with others determines the purposes and means of the processing of personal data (e.g., names, e-mail addresses, etc.).</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Retention Period</h3>
        <p className="text-gray-300 mb-6 leading-relaxed">Unless a more specific retention period is stated in this Privacy Policy, your personal data will remain with us until the purpose of data processing ceases to apply. If you make a legitimate request for deletion or revoke consent you have given, your data will be deleted unless we have other legally permissible reasons for retaining your personal data (e.g., tax or commercial retention periods); in such cases, deletion will occur once those reasons no longer apply.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Legal Bases of Processing</h3>
        <p className="text-gray-300 mb-6 leading-relaxed">If you have consented to data processing, we process your personal data based on Art. 6 (1) lit. a GDPR or Art. 9 (2) lit. a GDPR if special categories of data under Art. 9 (1) GDPR are processed. If you have given express consent to transfer personal data to third countries, processing is also based on Art. 49 (1) lit. a GDPR. If data processing is necessary for the performance of a contract or pre-contractual measures, we base processing on Art. 6 (1) lit. b GDPR. Furthermore, we process your data if required to comply with a legal obligation under Art. 6 (1) lit. c GDPR. Data processing may also be based on our legitimate interest under Art. 6 (1) lit. f GDPR. The specific legal basis for each case is explained in the following sections of this Privacy Policy.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Recipients of Personal Data</h3>
        <p className="text-gray-300 mb-6 leading-relaxed">In the course of our business activities, we work with various external parties. In some cases, it is necessary to transfer personal data to these external parties. We only share personal data with external parties if it is necessary for contract performance, if we are legally obligated to do so (e.g., sharing data with tax authorities), if we have a legitimate interest under Art. 6 (1) lit. f GDPR, or if another legal basis permits the data transfer. When using processors, we only transfer personal data based on a valid order processing agreement. In cases of joint processing, a joint processing agreement is concluded.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Revocation of Consent</h3>
        <p className="text-gray-300 mb-6 leading-relaxed">Many data processing operations are only possible with your express consent. You may revoke consent at any time. The lawfulness of processing carried out prior to revocation remains unaffected.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Right to Object</h3>
        <p className="text-gray-300 mb-4 leading-relaxed">If data processing is based on Art. 6 (1) lit. e or f GDPR, you have the right to object at any time for reasons arising from your particular situation to the processing of your personal data; this also applies to profiling based on these provisions. You may find the legal basis for each processing in this Privacy Policy. If you object, we will no longer process your personal data unless we can demonstrate compelling legitimate grounds for processing that override your interests, rights, and freedoms or if processing serves the establishment, exercise, or defense of legal claims (objection under Art. 21 (1) GDPR).</p>
        <p className="text-gray-300 mb-6 leading-relaxed">If your personal data are processed for direct marketing purposes, you have the right to object at any time to the processing of personal data concerning you for such marketing purposes; this also applies to profiling insofar as it is related to such direct marketing. If you object, your personal data will no longer be used for direct marketing (objection under Art. 21 (2) GDPR).</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Right to Lodge a Complaint</h3>
        <p className="text-gray-300 mb-6 leading-relaxed">In the event of violations of the GDPR, data subjects have the right to lodge a complaint with a supervisory authority, particularly in the Member State of their habitual residence, place of work, or place of the alleged infringement. The right to lodge a complaint is without prejudice to other administrative or judicial remedies.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Right to Data Portability</h3>
        <p className="text-gray-300 mb-6 leading-relaxed">You have the right to receive the personal data we process about you, which you have provided to us, in a structured, commonly used, and machine-readable format. You also have the right to transmit those data to another controller when technically feasible.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Right to Access, Rectification, and Erasure</h3>
        <p className="text-gray-300 mb-6 leading-relaxed">You have the right, at any time and free of charge under applicable law, to obtain access to your stored personal data, information about its origin and recipients, and the purpose of processing, and, if applicable, the right to rectification or erasure of this data. For this and other questions regarding personal data, you may contact us at any time.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Right to Restrict Processing</h3>
        <p className="text-gray-300 mb-4 leading-relaxed">You have the right to request the restriction of processing of your personal data. You may contact us at any time to do so. The right to restrict processing applies in the following cases:</p>
        <ul className="text-gray-300 mb-6 leading-relaxed list-disc list-inside space-y-2">
          <li>If you dispute the accuracy of your personal data stored with us, we usually need time to verify this. During the verification period, you have the right to request restriction of processing of your personal data.</li>
          <li>If processing of your personal data is unlawful, you may request restriction instead of erasure.</li>
          <li>If we no longer need your personal data but you need them to establish, exercise, or defend legal claims, you have the right to request restriction instead of erasure.</li>
          <li>If you have objected under Art. 21 (1) GDPR, a balance between your interests and ours must be conducted. As long as it is not clear whose interests prevail, you have the right to request restriction of processing of your personal data.</li>
        </ul>
        <p className="text-gray-300 mb-6 leading-relaxed">If processing of your personal data has been restricted, these data may only be processed—with the exception of storage—with your consent, to establish, exercise, or defend legal claims, to protect the rights of another natural or legal person, or for reasons of important public interest of the EU or a Member State.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">SSL/TLS Encryption</h3>
        <p className="text-gray-300 mb-4 leading-relaxed">For security reasons and to protect the transmission of confidential content, such as orders or inquiries you send to us as the site operator, this site uses SSL/TLS encryption. You can recognize an encrypted connection by the change from "http://" to "https://" and the lock icon in your browser's address bar.</p>
        <p className="text-gray-300 mb-8 leading-relaxed">When SSL/TLS encryption is activated, the data you transmit to us cannot be read by third parties.</p>
        <h2 className="text-2xl font-semibold mb-6 text-white">4. Data Collection on This Website</h2>
        <h3 className="text-xl font-semibold mb-4 text-white">Cookies</h3>
        <p className="text-gray-300 mb-4 leading-relaxed">Our websites use so-called "cookies." Cookies are small data packets and do not cause any damage to your device. They are stored either temporarily for the duration of a session (session cookies) or permanently (persistent cookies) on your device. Session cookies are automatically deleted at the end of your visit. Persistent cookies remain stored on your device until you delete them or they are automatically deleted by your web browser.</p>
        <p className="text-gray-300 mb-4 leading-relaxed">Cookies may come from us (first-party cookies) or from third-party companies (so-called third-party cookies). Third-party cookies enable the integration of certain services from third parties within websites (e.g., cookies for payment processing).</p>
        <p className="text-gray-300 mb-4 leading-relaxed">Cookies serve various functions. Numerous cookies are technically necessary because certain website functions would not work without them (e.g., shopping cart function or video display). Other cookies may be used to evaluate user behavior or for advertising purposes.</p>
        <p className="text-gray-300 mb-4 leading-relaxed">Cookies that are necessary for the electronic communication process, for the provision of certain services you specifically request (e.g., shopping cart function), or to optimize the website (e.g., cookies to measure web audience) are stored based on Art. 6 (1) lit. f GDPR if no other legal basis is specified. The site operator has a legitimate interest in the storage of necessary cookies for the technically error-free and optimized delivery of its services. If consent for the storage of cookies and similar recognition technologies has been requested, processing is carried out exclusively based on this consent (Art. 6 (1) lit. a GDPR and § 25 (1) TDDDG); consent may be revoked at any time.</p>
        <p className="text-gray-300 mb-4 leading-relaxed">You can configure your browser to inform you about the setting of cookies and only allow cookies on a case-by-case basis, to accept cookies for certain cases or in general, and to activate automatic deletion of cookies when closing the browser. Disabling cookies may limit the functionality of this website.</p>
        <p className="text-gray-300 mb-6 leading-relaxed">You can find which cookies and services are used on this website in this Privacy Policy.</p>
        <h3 className="text-xl font-semibold mb-4 text-white">Contact by E-Mail, Telephone, or Fax</h3>
        <p className="text-gray-300 mb-4 leading-relaxed">If you contact us by e-mail, telephone, or fax, your inquiry, including all personal data arising from it (name, inquiry), will be stored and processed by us for the purpose of handling your request. We will not share these data without your consent.</p>
        <p className="text-gray-300 mb-4 leading-relaxed">Processing of these data is based on Art. 6 (1) lit. b GDPR if your inquiry is related to the performance of a contract or is necessary for pre-contractual measures. In all other cases, processing is based on our legitimate interest in effectively handling inquiries addressed to us (Art. 6 (1) lit. f GDPR) or on your consent (Art. 6 (1) lit. a GDPR) if requested; consent may be revoked at any time.</p>
        <p className="text-gray-300 mb-4 leading-relaxed">The data you send to us via contact requests remain with us until you request deletion, revoke your consent to storage, or the purpose of data storage no longer applies (e.g., after your inquiry has been handled). Mandatory legal provisions—particularly statutory retention periods—remain unaffected.</p>
        <p className="text-gray-400 text-sm">Source: <a href="https://www.e-recht24.de" className="text-[#7A1CAC] hover:text-[#AD49E1] transition-colors duration-200 underline">https://www.e-recht24.de</a></p>
      </div>
    </div>
  );
}
